---
# defaults/main.yml
hypervisor_ip: "same"
interface_name: "cloudbr0"
netmask_prefix: "24"
gateway: "10.0.1.1"
dns_server: "10.0.1.11 10.0.1.12"

# Hostname settings
hostdns: "ltestkvm001"
domain_name: "lab.local"