---
# Default variables for kvm_install
hypervisor_ip: "same"
interface_name: "ens33" # Update this with your actual interface (e.g., enp1s0)
gateway: "10.0.1.1"
dns_server: "10.0.1.11 10.0.1.12"
netmask_prefix: "24"