---
# Default variables for kvm_install
hypervisor_ip: "same"
interface_name: "cloudbr0"
dns_server: "10.0.1.11 10.0.1.12"
netmask_prefix: "24"

# Hostname settings
hostdns: "ltestkvm001"
domain_name: "local.lab"